import type { App } from './types'

export const APPS: App[] = [
  {
    id: 'pulse-analytics',
    name: 'Pulse Analytics',
    tagline: 'Realtime SaaS metrics with anomaly alerts',
    description: [
      'Pulse Analytics streams your product metrics into one living wall: activation funnels, retention curves, MRR waterfalls and per-cohort health, all rendered at 60fps on a canvas pipeline that handles millions of points without breaking a sweat.',
      'The built-in anomaly engine learns each metric\u2019s weekly rhythm and pings you the moment something drifts \u2014 a signup spike, a churn blip, a checkout slowdown. Every alert links to the exact segment and time window, so debugging starts in seconds, not standups.',
      'Connect Postgres, Stripe, Segment or any webhook in minutes. Dashboards are plain JSON under the hood, which means they diff cleanly, review like code and regenerate on demand.',
    ],
    developer: 'Latent Works',
    category: 'Dashboards',
    tags: ['analytics', 'saas', 'charts', 'realtime', 'metrics'],
    rating: 4.8,
    ratingCount: 12840,
    downloads: 486000,
    sizeMB: 18.2,
    version: '3.4.1',
    updatedDaysAgo: 2,
    colors: ['#06b6d4', '#3b82f6'],
    icon: 'Activity',
    demoId: 'dashboard',
    editorsChoice: true,
    features: [
      'Streaming charts at 60fps with LTTB downsampling',
      'Anomaly detection tuned per-metric with quiet hours',
      'Share live dashboards via signed read-only links',
      'Everything-as-JSON: dashboards diff and code-review cleanly',
    ],
    changelog: [
      { v: '3.4.1', notes: ['Faster funnel rendering for ranges over 90 days', 'Fixed timezone edge case in cohort grid'] },
      { v: '3.4.0', notes: ['New MRR waterfall block', 'Alert routing to Slack threads'] },
    ],
  },
  {
    id: 'opsdeck',
    name: 'OpsDeck',
    tagline: 'NOC wall for clusters, queues and budgets',
    description: [
      'OpsDeck is the mission-control dashboard for small infra teams: node maps, queue depths, error budgets and cost burn on a single dense screen designed to be readable from across the room.',
      'SLO tracking is first-class. Define an objective once and OpsDeck derives burn rates, pages you only when speed matters, and shows remaining error budget right next to deploy markers so you can see exactly which release ate it.',
      'Runs anywhere a browser does; state syncs peer-to-peer between viewers, so everyone on call sees the same wall without a backend.',
    ],
    developer: 'Synthetic Dept.',
    category: 'Dashboards',
    tags: ['devops', 'monitoring', 'slo', 'infra', 'kubernetes'],
    rating: 4.6,
    ratingCount: 5210,
    downloads: 152300,
    sizeMB: 24.7,
    version: '2.9.0',
    updatedDaysAgo: 5,
    colors: ['#64748b', '#38bdf8'],
    icon: 'Server',
    features: [
      'Node topology map with live health halo',
      'Error-budget bars beside deploy markers',
      'P2P state sync, zero backend required',
      'Cost burn-down forecast per service',
    ],
    changelog: [{ v: '2.9.0', notes: ['Queue-depth heatstrips', 'Dark-room dimming mode'] }],
  },
  {
    id: 'ledgerly',
    name: 'Ledgerly Finance OS',
    tagline: 'Accounts, budgets and Monte-Carlo forecasts',
    description: [
      'Ledgerly turns raw statements into a double-entry ledger you can actually trust, then layers budgets, sinking funds and what-if forecasting on top. Import CSVs from 400+ banks or point it at a folder of receipts.',
      'The forecast engine runs ten thousand Monte-Carlo paths against your income volatility so "can I afford this?" becomes a probability, not a vibe.',
      'Fully local-first: your numbers never leave the device unless you enable encrypted sync.',
    ],
    developer: 'Gradient House',
    category: 'Dashboards',
    tags: ['finance', 'budgeting', 'forecasting', 'personal'],
    rating: 4.7,
    ratingCount: 8930,
    downloads: 233800,
    sizeMB: 31.4,
    version: '5.1.3',
    updatedDaysAgo: 1,
    colors: ['#8b5cf6', '#6366f1'],
    icon: 'Wallet',
    features: [
      'Rules engine that learns your categorization',
      'Monte-Carlo affordability checks',
      'Local-first with optional E2E sync',
      'Receipt OCR that works offline',
    ],
    changelog: [{ v: '5.1.3', notes: ['Joint-budget merge for households', 'Faster CSV import'] }],
  },
  {
    id: 'habit-graph',
    name: 'Habit Graph',
    tagline: 'Streaks, correlations and honest trends',
    description: [
      'Habit Graph tracks routines as a force-directed graph instead of a checklist: sleep pulls on gym, gym pulls on focus, focus pulls on mood. Over weeks the structure of your behavior emerges visually.',
      'Correlation hints are computed locally with lagged regression and shown with confidence bands, because a habit app that lies with statistics is worse than no app at all.',
    ],
    developer: 'Emergent Labs',
    category: 'Dashboards',
    tags: ['habits', 'quantified-self', 'health', 'streaks'],
    rating: 4.5,
    ratingCount: 3410,
    downloads: 98100,
    sizeMB: 12.8,
    version: '1.8.2',
    updatedDaysAgo: 12,
    colors: ['#10b981', '#84cc16'],
    icon: 'TrendingUp',
    features: ['Force-directed habit graph', 'Lagged correlation with confidence bands', 'Gentle streak repair for travel days'],
    changelog: [{ v: '1.8.2', notes: ['Weekly digest email', 'Graph layout perf fix'] }],
  },
  {
    id: 'carbon-lens',
    name: 'CarbonLens',
    tagline: 'Scope 1\u20133 emissions, finally legible',
    description: [
      'CarbonLens ingests invoices, flights and cloud bills and maps them to emission factors automatically, giving your team a defensible footprint number with full drill-down to the line item.',
      'Scenario mode lets you price reductions before committing: shift a workload region, swap a supplier, cut one flight lane and watch the tCO\u2082e curve respond instantly.',
    ],
    developer: 'GreenToken Studio',
    category: 'Dashboards',
    tags: ['climate', 'esg', 'reporting', 'cloud'],
    rating: 4.4,
    ratingCount: 1980,
    downloads: 47600,
    sizeMB: 15.1,
    version: '2.2.0',
    updatedDaysAgo: 19,
    colors: ['#14b8a6', '#22c55e'],
    icon: 'Leaf',
    features: ['Auto-mapped emission factors', 'Cloud bill ingestion (AWS/GCP/Azure)', 'Reduction scenario sandbox'],
    changelog: [{ v: '2.2.0', notes: ['CSRD-ready export pack'] }],
  },
  {
    id: 'crew-roster',
    name: 'Crew Roster',
    tagline: 'Capacity planning with fair auto-shifts',
    description: [
      'Crew Roster balances skills, contracts, time-off and preferences into rotas that people actually accept. The solver optimizes fairness explicitly: consecutive weekend load is equalized before total hours are.',
      'Swap requests resolve themselves when rules allow it, and every change keeps an audit trail for compliance.',
    ],
    developer: 'Backprop Bros',
    category: 'Dashboards',
    tags: ['scheduling', 'hr', 'teams', 'shifts'],
    rating: 4.3,
    ratingCount: 1420,
    downloads: 39200,
    sizeMB: 21.0,
    version: '4.0.1',
    updatedDaysAgo: 8,
    colors: ['#f97316', '#f59e0b'],
    icon: 'Users',
    features: ['Constraint solver with fairness objective', 'Self-service swaps with rule guardrails', 'Compliance audit trail'],
    changelog: [{ v: '4.0.1', notes: ['Night-shift fatigue weighting'] }],
  },
  {
    id: 'market-mosaic',
    name: 'Market Mosaic',
    tagline: 'Portfolio heatmap across 40 exchanges',
    description: [
      'Market Mosaic renders your whole portfolio as a living treemap sized by weight and colored by momentum, with drill-downs from asset class to single position in two clicks.',
      'Risk overlays show correlation clusters and concentration warnings inline, and the replay mode scrubs through history so you can re-watch any quarter like game footage.',
    ],
    developer: 'Softmax Society',
    category: 'Dashboards',
    tags: ['investing', 'markets', 'portfolio', 'heatmap'],
    rating: 4.6,
    ratingCount: 6740,
    downloads: 187500,
    sizeMB: 27.3,
    version: '6.2.0',
    updatedDaysAgo: 3,
    colors: ['#ef4444', '#f43f5e'],
    icon: 'ChartCandlestick',
    features: ['Momentum treemap with drill-down', 'Correlation clustering overlay', 'Historical replay scrubber'],
    permissions: ["Read-only market data feeds"],
    changelog: [{ v: '6.2.0', notes: ['Options greeks tiles', 'Replay speed control'] }],
  },

  {
    id: 'neon-serpent',
    name: 'Neon Serpent',
    tagline: 'Arcade snake reborn in synthwave',
    description: [
      'Neon Serpent is snake the way a model dreams it: chromatic trails, beat-synced obstacles and a combo system that rewards threading impossible gaps at full sprint.',
      'Twelve handcrafted grids plus an endless generator that composes new layouts from your last death, so every run quietly trains on your weaknesses.',
      'Global leaderboards are verified server-side; replays are tiny seed files you can share as URLs.',
    ],
    developer: 'Latent Arcade',
    category: 'Games',
    tags: ['arcade', 'snake', 'retro', 'leaderboards'],
    rating: 4.9,
    ratingCount: 21450,
    downloads: 892000,
    sizeMB: 9.6,
    version: '2.5.0',
    updatedDaysAgo: 1,
    colors: ['#d946ef', '#22d3ee'],
    icon: 'Gamepad2',
    demoId: 'snake',
    editorsChoice: true,
    features: [
      'Beat-synced obstacle choreography',
      'Endless generator trained on your deaths',
      'Seed-based replays shareable as links',
    ],
    changelog: [
      { v: '2.5.0', notes: ['New grid: Split Circuit', 'Ghost racer vs your best run'] },
      { v: '2.4.2', notes: ['Touch swipe tuning', 'Reduced motion option'] },
    ],
  },
  {
    id: 'slide-2048',
    name: '2048 \u221e',
    tagline: 'Merge puzzles on a cosmic grid',
    description: [
      'The classic tile merger, rebuilt with buttery physics, five board shapes and an infinity mode where matched tiles collapse into star-stuff and the board slowly grows.',
      'Daily seeds put every player on identical shuffle streams; a hint engine can explain the best move in plain language when you\u2019re stuck.',
    ],
    developer: 'Vibe Coded Inc.',
    category: 'Games',
    tags: ['puzzle', '2048', 'casual', 'daily'],
    rating: 4.7,
    ratingCount: 15320,
    downloads: 640300,
    sizeMB: 6.8,
    version: '3.1.0',
    updatedDaysAgo: 6,
    colors: ['#f59e0b', '#f97316'],
    icon: 'Grid3x3',
    demoId: 'g2048',
    features: ['Infinity collapse mode', 'Shared daily seeds', 'Plain-language move hints'],
    changelog: [{ v: '3.1.0', notes: ['Hexagonal board shape', 'Haptics on supported devices'] }],
  },
  {
    id: 'starfall-tactics',
    name: 'Starfall Tactics',
    tagline: 'Turn-based skirmishes on generated maps',
    description: [
      'A compact tactics game about positioning: six units, elevation, overwatch cones and fog. Maps generate from seeds so skirmishes stay fresh, and the AI opponent telegraphs its intent honestly instead of cheating.',
      'Cross-platform save sync and a puzzle mode of 200 curated tactical problems round it out.',
    ],
    developer: 'Token Forge Studio',
    category: 'Games',
    tags: ['tactics', 'strategy', 'turn-based', 'procedural'],
    rating: 4.5,
    ratingCount: 4820,
    downloads: 121700,
    sizeMB: 84.2,
    version: '1.6.4',
    updatedDaysAgo: 15,
    colors: ['#6366f1', '#a855f7'],
    icon: 'Swords',
    features: ['Honest AI that shows intent', 'Seeded procedural battlefields', '200-puzzle tactics campaign'],
    changelog: [{ v: '1.6.4', notes: ['Overwatch balance pass'] }],
  },
  {
    id: 'dungeon-of-prompts',
    name: 'Dungeon of Prompts',
    tagline: 'Roguelike where spells are prompts',
    description: [
      'Every spell in this crawler is a prompt you compose from found fragments. "A rain of small sharp moons" does exactly what it says, once. Wording matters, ambiguity bites, and the dungeon remembers.',
      'Deterministic local generation means runs are reproducible from seeds, no network required after install.',
    ],
    developer: 'Prompt & Circumstance',
    category: 'Games',
    tags: ['roguelike', 'dungeon', 'language', 'indie'],
    rating: 4.6,
    ratingCount: 3910,
    downloads: 88400,
    sizeMB: 47.9,
    version: '0.9.8',
    updatedDaysAgo: 9,
    colors: ['#059669', '#14b8a6'],
    icon: 'Castle',
    features: ['Compose spells from language fragments', 'Deterministic seeded runs', 'Offline-first generation'],
    changelog: [{ v: '0.9.8', notes: ['Fragment fusion table v2'] }],
  },
  {
    id: 'orbit-golf',
    name: 'Orbit Golf',
    tagline: 'Gravity slingshots across 120 worlds',
    description: [
      'Mini golf where every planet has mass. Read the field lines, bank off moons, sink the hole in as few burns as possible. The physics is real n-body integration at fixed timestep, tuned until trick shots feel earned.',
      'Level editor included; published holes appear in the community rotation with ratings.',
    ],
    developer: 'Hallucination Free LLC',
    category: 'Games',
    tags: ['physics', 'golf', 'space', 'chill'],
    rating: 4.4,
    ratingCount: 2760,
    downloads: 76200,
    sizeMB: 38.5,
    version: '2.0.3',
    updatedDaysAgo: 22,
    colors: ['#0ea5e9', '#2563eb'],
    icon: 'Orbit',
    features: ['True n-body physics', '120 hand-tuned worlds', 'Community level rotation'],
    changelog: [{ v: '2.0.3', notes: ['Editor undo stack'] }],
  },
  {
    id: 'pixel-pet-hotel',
    name: 'Pixel Pet Hotel',
    tagline: 'Raise glitchy pets in a tiny tower',
    description: [
      'A gentle idle sim where residents are procedurally pixelated creatures with moods, quirks and opinions about wallpaper. Check in twice a day or let the concierge AI run the desk while you\u2019re away.',
      'No energy timers, no ads, just a hotel that hums along and occasionally mails you postcards from your own pets.',
    ],
    developer: 'Cozy Compute',
    category: 'Games',
    tags: ['idle', 'cozy', 'pixel', 'pets'],
    rating: 4.8,
    ratingCount: 9870,
    downloads: 402600,
    sizeMB: 52.1,
    version: '1.11.0',
    updatedDaysAgo: 4,
    colors: ['#ec4899', '#fb7185'],
    icon: 'PawPrint',
    features: ['Procedural pixel pets with personalities', 'Offline progress with concierge mode', 'Postcard generator'],
    changelog: [{ v: '1.11.0', notes: ['Rooftop garden floor', 'Pet opinion system v2'] }],
  },
  {
    id: 'rhythm-rift',
    name: 'Rhythm Rift',
    tagline: 'Runner synced to generative synthwave',
    description: [
      'An endless runner whose soundtrack is composed live: rifts tear open on downbeats, platforms phase on fills, and your best runs get exported as actual songs.',
      'Difficulty adapts to your heart rate if you wear a monitor, backing off before frustration and pushing during flow states.',
    ],
    developer: 'Latent Arcade',
    category: 'Games',
    tags: ['rhythm', 'runner', 'music', 'endless'],
    rating: 4.3,
    ratingCount: 3120,
    downloads: 94300,
    sizeMB: 61.7,
    version: '1.4.1',
    updatedDaysAgo: 17,
    colors: ['#a855f7', '#e879f9'],
    icon: 'Music',
    features: ['Live-composed generative soundtrack', 'Export runs as audio', 'HR-adaptive difficulty'],
    changelog: [{ v: '1.4.1', notes: ['Song export normalization'] }],
  },
  {
    id: 'wordforge-daily',
    name: 'Wordforge Daily',
    tagline: 'A constructed-language puzzle at midnight',
    description: [
      'Each day Wordforge invents a tiny language \u2014 twelve roots, a grammar quirk, a writing direction \u2014 and challenges you to decode a message written in it before midnight.',
      'Past languages remain playable forever and the community lexicon documents them all, wiki-style.',
    ],
    developer: 'Prompt & Circumstance',
    category: 'Games',
    tags: ['word', 'daily', 'languages', 'logic'],
    rating: 4.5,
    ratingCount: 2280,
    downloads: 58900,
    sizeMB: 11.3,
    version: '1.7.0',
    updatedDaysAgo: 11,
    colors: ['#65a30d', '#10b981'],
    icon: 'Type',
    features: ['Daily generated micro-languages', 'Permanent archive + wiki', 'Hint ladders that teach grammar'],
    changelog: [{ v: '1.7.0', notes: ['Right-to-left scripts'] }],
  },

  {
    id: 'glasskit',
    name: 'Glasskit',
    tagline: '240 glassmorphic components, tokens included',
    description: [
      'Glasskit is a complete glassmorphism design system: buttons, sheets, navbars, players and charts, all built from three primitives and driven entirely by design tokens.',
      'Accessibility isn\u2019t an afterthought \u2014 every surface ships with computed contrast fallbacks that thicken blur into solid color when readability drops below WCAG AA.',
      'Copy any component as React, Vue or plain HTML from the integrated playground.',
    ],
    developer: 'Mira Chen & o3',
    category: 'UIs & Components',
    tags: ['design-system', 'components', 'glassmorphism', 'tokens'],
    rating: 4.9,
    ratingCount: 7420,
    downloads: 298100,
    sizeMB: 14.6,
    version: '4.2.0',
    updatedDaysAgo: 2,
    colors: ['#d946ef', '#8b5cf6'],
    icon: 'Layers',
    editorsChoice: true,
    features: [
      '240 components from 3 primitives',
      'Automatic AA contrast fallbacks under blur',
      'React / Vue / HTML export',
    ],
    changelog: [{ v: '4.2.0', notes: ['Sheet stacking contexts fixed', 'New player components'] }],
  },
  {
    id: 'kanbanly',
    name: 'Kanbanly',
    tagline: 'Boards that rearrange themselves',
    description: [
      'Kanbanly watches how work actually flows and suggests board surgery: columns to split, WIP limits to enforce, cards that have been silently blocked for days.',
      'Keyboard-first, offline-capable, and fast enough that moving a card feels physical. Multi-select bulk actions, swimlanes, and saved filters included.',
    ],
    developer: 'Flowstate Systems',
    category: 'UIs & Components',
    tags: ['kanban', 'productivity', 'board', 'wip'],
    rating: 4.6,
    ratingCount: 4310,
    downloads: 143900,
    sizeMB: 13.2,
    version: '2.3.2',
    updatedDaysAgo: 7,
    colors: ['#3b82f6', '#8b5cf6'],
    icon: 'SquareKanban',
    demoId: 'kanban',
    features: ['Flow-aware suggestions', 'Keyboard-first everything', 'Offline with CRDT sync'],
    changelog: [{ v: '2.3.2', notes: ['Swimlane collapse memory'] }],
  },
  {
    id: 'formflow-studio',
    name: 'Formflow Studio',
    tagline: 'Drag-drop forms with conditional logic',
    description: [
      'Build multi-step forms with branching logic, computed fields and validation graphs, then embed anywhere with one script tag or export schema-only for your stack.',
      'Submissions stream into a realtime response explorer with drop-off analytics per step, so you can see exactly where people hesitate.',
    ],
    developer: 'Flowstate Systems',
    category: 'UIs & Components',
    tags: ['forms', 'builder', 'surveys', 'validation'],
    rating: 4.5,
    ratingCount: 3640,
    downloads: 118600,
    sizeMB: 19.4,
    version: '3.7.1',
    updatedDaysAgo: 10,
    colors: ['#0ea5e9', '#6366f1'],
    icon: 'ClipboardList',
    features: ['Visual branch builder', 'Step-level drop-off analytics', 'Schema export, zero lock-in'],
    changelog: [{ v: '3.7.1', notes: ['Matrix question type'] }],
  },
  {
    id: 'onboardly',
    name: 'Onboardly',
    tagline: 'Tours, tooltips and checklists kit',
    description: [
      'Ship product tours that respect users: spotlight steps anchored to real elements, deferred tooltips that wait for intent, and checklists that persist across sessions without nagging.',
      'Every flow ships with skip-resilience \u2014 partial completions resume gracefully after layout shifts or route changes.',
    ],
    developer: 'Emergent Labs',
    category: 'UIs & Components',
    tags: ['onboarding', 'tour', 'ux', 'checklist'],
    rating: 4.4,
    ratingCount: 2110,
    downloads: 66800,
    sizeMB: 8.9,
    version: '1.9.0',
    updatedDaysAgo: 13,
    colors: ['#f43f5e', '#ec4899'],
    icon: 'Map',
    features: ['Element-anchored spotlights', 'Intent-deferred tooltips', 'Skip-resilient resume'],
    changelog: [{ v: '1.9.0', notes: ['Checklist progress rings'] }],
  },
  {
    id: 'aurora-tokens',
    name: 'Aurora Tokens',
    tagline: 'Design tokens, Figma to code in one click',
    description: [
      'Aurora compiles a single token graph into CSS variables, Tailwind presets, Swift and Kotlin themes simultaneously, keeping every platform honest to one source of truth.',
      'Contrast linting runs on every commit: pairs that fail AA are flagged in the PR diff itself.',
    ],
    developer: 'Gradient House',
    category: 'UIs & Components',
    tags: ['tokens', 'theming', 'figma', 'css'],
    rating: 4.7,
    ratingCount: 2890,
    downloads: 87300,
    sizeMB: 7.4,
    version: '2.8.0',
    updatedDaysAgo: 5,
    colors: ['#6366f1', '#22d3ee'],
    icon: 'Palette',
    features: ['One graph, four platform targets', 'Contrast lint in CI', 'Semantic alias layers'],
    changelog: [{ v: '2.8.0', notes: ['Kotlin theme target'] }],
  },
  {
    id: 'motion-menu',
    name: 'Motion Menu',
    tagline: '60 spring-animated navigation patterns',
    description: [
      'A living catalog of navigation motion: drawers, docks, morphing tabs, command palettes \u2014 each tuned with spring physics and shipped as copy-paste code with reduced-motion variants.',
      'Scrub any pattern\u2019s stiffness and damping in the playground until it feels right, then export the exact spring constants.',
    ],
    developer: 'Studio Parallax',
    category: 'UIs & Components',
    tags: ['animation', 'navigation', 'springs', 'patterns'],
    rating: 4.6,
    ratingCount: 1980,
    downloads: 57200,
    sizeMB: 9.8,
    version: '1.5.2',
    updatedDaysAgo: 16,
    colors: ['#a78bfa', '#e879f9'],
    icon: 'Navigation',
    features: ['Spring scrubbing playground', 'Reduced-motion variant for every pattern', 'Framework-agnostic exports'],
    changelog: [{ v: '1.5.2', notes: ['Command palette pattern'] }],
  },
  {
    id: 'cardstack-ui',
    name: 'Cardstack UI',
    tagline: 'Bento-grid card system with live theming',
    description: [
      'Cardstack gives you twenty bento card archetypes \u2014 stat, sparkline, list, media, gauge \u2014 that compose into responsive dashboards with zero media-query bookkeeping.',
      'Themes compile to CSS custom properties at build time; switching palettes costs nothing at runtime.',
    ],
    developer: 'Studio Parallax',
    category: 'UIs & Components',
    tags: ['bento', 'cards', 'layout', 'theming'],
    rating: 4.3,
    ratingCount: 1540,
    downloads: 44100,
    sizeMB: 6.2,
    version: '1.3.0',
    updatedDaysAgo: 25,
    colors: ['#fbbf24', '#fb923c'],
    icon: 'LayoutDashboard',
    features: ['20 bento archetypes', 'Build-time theme compilation', 'Container-query responsive'],
    changelog: [{ v: '1.3.0', notes: ['Gauge card archetype'] }],
  },

  {
    id: 'warpfile',
    name: 'Warpfile',
    tagline: 'A file manager that thinks in keystrokes',
    description: [
      'Warpfile is a terminal file manager with fuzzy everything: jump to any file within three keystrokes, preview anything text-shaped instantly, and bulk-rename with a live regex scratchpad.',
      'The TUI renders at native refresh with zero flicker, remembers per-directory layouts, and speaks plain SSH \u2014 remote hosts feel local.',
      'This store listing includes a fully interactive demo. Open it and drive the interface yourself.',
    ],
    developer: 'Terminal Zen',
    category: 'TUIs & CLIs',
    tags: ['terminal', 'file-manager', 'tui', 'keyboard'],
    rating: 4.8,
    ratingCount: 6120,
    downloads: 176400,
    sizeMB: 4.1,
    version: '3.2.0',
    updatedDaysAgo: 1,
    colors: ['#22c55e', '#10b981'],
    icon: 'FolderTree',
    demoId: 'tui',
    editorsChoice: true,
    features: [
      'Fuzzy jump, fuzzy filter, fuzzy everything',
      'Live regex rename scratchpad',
      'Native-refresh flicker-free rendering',
    ],
    changelog: [{ v: '3.2.0', notes: ['Archive mount previews', 'j/k half-page scrolling'] }],
  },
  {
    id: 'gitsage',
    name: 'GitSage',
    tagline: 'Git TUI that explains diffs plainly',
    description: [
      'GitSage wraps git in a two-pane terminal UI: commits left, meaning right. Select any hunk and get a plain-language explanation of what changed and why it probably matters.',
      'Interactive rebase gets a drag-to-reorder timeline with instant conflict forecasting before you commit to the operation.',
    ],
    developer: 'Terminal Zen',
    category: 'TUIs & CLIs',
    tags: ['git', 'terminal', 'diff', 'rebase'],
    rating: 4.7,
    ratingCount: 4980,
    downloads: 132700,
    sizeMB: 7.9,
    version: '2.4.0',
    updatedDaysAgo: 6,
    colors: ['#f97316', '#ef4444'],
    icon: 'GitBranch',
    features: ['Plain-language diff explanations', 'Rebase timeline with conflict forecast', 'Blame heat view'],
    changelog: [{ v: '2.4.0', notes: ['Stacked-diff navigator'] }],
  },
  {
    id: 'syspulse-tui',
    name: 'SysPulse',
    tagline: 'System monitor with taste',
    description: [
      'CPU, memory, GPU, network and thermals in one dense terminal dashboard with configurable modules, sparkline histories and process triage that groups by service instead of PID soup.',
      'Ships with themes that survive bad terminals and an alert strip that glows when thresholds breach.',
    ],
    developer: 'Softmax Society',
    category: 'TUIs & CLIs',
    tags: ['system', 'monitor', 'htop', 'terminal'],
    rating: 4.6,
    ratingCount: 3540,
    downloads: 108200,
    sizeMB: 3.6,
    version: '2.1.1',
    updatedDaysAgo: 4,
    colors: ['#14b8a6', '#06b6d4'],
    icon: 'Cpu',
    features: ['Service-grouped process triage', 'Thermal + power modules', 'Theme engine for bad terminals'],
    changelog: [{ v: '2.1.1', notes: ['GPU module for Apple Silicon'] }],
  },
  {
    id: 'notesmith',
    name: 'Notesmith CLI',
    tagline: 'Markdown notes with query superpowers',
    description: [
      'Notesmith indexes your markdown vault into a queryable graph: backlinks, tasks scattered across files, and a TUI search that understands "tasks due this week mentioning Q3".',
      'Files stay plain markdown on disk; the index rebuilds incrementally in milliseconds.',
    ],
    developer: 'Inkwell Automata',
    category: 'TUIs & CLIs',
    tags: ['notes', 'markdown', 'search', 'zettelkasten'],
    rating: 4.5,
    ratingCount: 2730,
    downloads: 71800,
    sizeMB: 5.4,
    version: '1.12.0',
    updatedDaysAgo: 9,
    colors: ['#84cc16', '#22c55e'],
    icon: 'NotebookPen',
    features: ['Natural-language vault queries', 'Incremental millisecond indexing', 'Task rollup across files'],
    changelog: [{ v: '1.12.0', notes: ['Daily-notes templates'] }],
  },
  {
    id: 'bandwidth-bandit',
    name: 'Bandwidth Bandit',
    tagline: 'Per-process network accounting live',
    description: [
      'See exactly which process is saturating your link, with per-connection breakdowns, historical caps and a kill-switch TUI panel for misbehaving apps.',
      'Works via eBPF on Linux and a helper daemon on macOS; no kernel patches, no root persistence beyond opt-in.',
    ],
    developer: 'Backprop Bros',
    category: 'TUIs & CLIs',
    tags: ['network', 'bandwidth', 'ebpf', 'monitor'],
    rating: 4.4,
    ratingCount: 1890,
    downloads: 52600,
    sizeMB: 4.8,
    version: '1.6.3',
    updatedDaysAgo: 20,
    colors: ['#38bdf8', '#818cf8'],
    icon: 'Network',
    features: ['Per-process live accounting', 'Connection kill-switch panel', 'Monthly cap projections'],
    changelog: [{ v: '1.6.3', notes: ['IPv6 label polish'] }],
  },
  {
    id: 'shellcast',
    name: 'ShellCast',
    tagline: 'Record terminal sessions as tiny SVGs',
    description: [
      'ShellCast captures a terminal session and emits a self-contained animated SVG a fraction of the size of video \u2014 perfect for READMEs, issues and docs.',
      'Cursor, themes and typing cadence are preserved; output is deterministic and diffable.',
    ],
    developer: 'Inkwell Automata',
    category: 'TUIs & CLIs',
    tags: ['recording', 'svg', 'docs', 'terminal'],
    rating: 4.3,
    ratingCount: 1240,
    downloads: 33100,
    sizeMB: 2.9,
    version: '0.8.4',
    updatedDaysAgo: 31,
    colors: ['#facc15', '#a3e635'],
    icon: 'Clapperboard',
    features: ['Animated SVG output', 'Deterministic, diffable captures', 'README-friendly embedding'],
    changelog: [{ v: '0.8.4', notes: ['Typing cadence smoothing'] }],
  },

  {
    id: 'evaldeck',
    name: 'EvalDeck',
    tagline: 'Eval harness for shipping with confidence',
    description: [
      'EvalDeck turns evals from a research chore into a CI gate: define suites as declarative YAML, run them against any endpoint, and gate merges on pass-rate regressions the way you gate tests.',
      'Suites compose \u2014 mix golden sets, rubric graders, pairwise A/B duels and perturbation fuzzers \u2014 then render diffs between runs side-by-side so you always know what a prompt change actually bought you.',
      'The bundled demo lets you run a miniature suite right here in the store. Try it.',
    ],
    developer: 'Benchmark Guild',
    category: 'Harnesses & Evals',
    tags: ['evals', 'testing', 'ci', 'llm', 'quality'],
    rating: 4.8,
    ratingCount: 4460,
    downloads: 96700,
    sizeMB: 22.6,
    version: '2.0.1',
    updatedDaysAgo: 3,
    colors: ['#f59e0b', '#ef4444'],
    icon: 'FlaskConical',
    demoId: 'evaldeck',
    editorsChoice: true,
    features: [
      'Declarative YAML suites that compose',
      'Pairwise duel grading with tie detection',
      'Run-diff viewer: side-by-side verdict flips',
      'CI gate mode with regression thresholds',
    ],
    changelog: [
      { v: '2.0.1', notes: ['Duel grader tie-break policies', 'Suite import from JSONL'] },
      { v: '2.0.0', notes: ['Perturbation fuzzer blocks', 'Parallel endpoint racing'] },
    ],
  },
  {
    id: 'redteam-range',
    name: 'RedTeam Range',
    tagline: 'Adversarial prompt firing range',
    description: [
      'A structured range of adversarial techniques \u2014 injection, exfiltration, role confusion, tool abuse \u2014 organized by taxonomy with severity scores, so red-teaming becomes repeatable rather than folklore.',
      'Findings export as reproducible cases that plug straight into EvalDeck suites.',
    ],
    developer: 'Benchmark Guild',
    category: 'Harnesses & Evals',
    tags: ['security', 'red-team', 'prompts', 'safety'],
    rating: 4.6,
    ratingCount: 2130,
    downloads: 41800,
    sizeMB: 17.8,
    version: '1.4.0',
    updatedDaysAgo: 14,
    colors: ['#ef4444', '#a855f7'],
    icon: 'ShieldHalf',
    features: ['Taxonomized attack library', 'Severity-scored findings', 'EvalDeck-compatible exports'],
    changelog: [{ v: '1.4.0', notes: ['Multi-turn escalation chains'] }],
  },
  {
    id: 'benchlite',
    name: 'BenchLite',
    tagline: 'Benchmark runner that fits in a binary',
    description: [
      'BenchLite runs standard benchmark slices against local models with warm/cold cache separation, variance tracking and automatic outlier quarantine.',
      'Results land in a local leaderboard database so you can plot capability-per-dollar across checkpoints over time.',
    ],
    developer: 'Softmax Society',
    category: 'Harnesses & Evals',
    tags: ['benchmarks', 'local-models', 'metrics', 'cli'],
    rating: 4.4,
    ratingCount: 1670,
    downloads: 36400,
    sizeMB: 11.9,
    version: '1.9.2',
    updatedDaysAgo: 18,
    colors: ['#8b5cf6', '#d946ef'],
    icon: 'Gauge',
    features: ['Warm/cold cache separation', 'Automatic outlier quarantine', 'Capability-per-dollar plots'],
    changelog: [{ v: '1.9.2', notes: ['Tokenizer mismatch guards'] }],
  },
  {
    id: 'tracelens',
    name: 'TraceLens',
    tagline: 'Trace inspector for agent systems',
    description: [
      'TraceLens ingests OpenTelemetry spans from multi-agent systems and reconstructs the conversation as a waterfall: every tool call, retry, token count and cost, attributable to the exact span that caused it.',
      'Diff mode overlays two traces to expose where a pipeline started diverging \u2014 invaluable after prompt changes.',
    ],
    developer: 'Latent Works',
    category: 'Harnesses & Evals',
    tags: ['tracing', 'agents', 'otel', 'debugging'],
    rating: 4.7,
    ratingCount: 2980,
    downloads: 68900,
    sizeMB: 16.3,
    version: '1.10.0',
    updatedDaysAgo: 7,
    colors: ['#22d3ee', '#34d399'],
    icon: 'Waypoints',
    features: ['Waterfall reconstruction from OTel spans', 'Per-span token and cost attribution', 'Two-trace divergence overlay'],
    changelog: [{ v: '1.10.0', notes: ['Streaming span support'] }],
  },

  {
    id: 'inbox-zeroer',
    name: 'Inbox Zeroer',
    tagline: 'Email triage agent with receipts',
    description: [
      'Inbox Zeroer drafts replies, archives noise and files the rest \u2014 but every action arrives as a reversible receipt batch you approve in one glance, so trust compounds without surrendering control.',
      'It learns your voice from sent mail locally; drafts sound like you on a good day, not like a press release.',
    ],
    developer: 'Minion Systems',
    category: 'Agents & Automation',
    tags: ['email', 'agent', 'triage', 'productivity'],
    rating: 4.5,
    ratingCount: 5820,
    downloads: 210400,
    sizeMB: 13.7,
    version: '3.3.0',
    updatedDaysAgo: 2,
    colors: ['#3b82f6', '#22d3ee'],
    icon: 'Mail',
    features: ['Reversible receipt-batch actions', 'Local voice matching from sent mail', 'Snooze with return conditions'],
    permissions: ["Read email metadata","Draft replies for approval"],
    changelog: [{ v: '3.3.0', notes: ['Thread-level digest mode'] }],
  },
  {
    id: 'scraperbot-studio',
    name: 'ScraperBot Studio',
    tagline: 'Visual pipelines for web data',
    description: [
      'Draw extraction pipelines on top of live page previews: click elements, add pagination loops, schedule runs and ship results to Sheets, S3 or a webhook.',
      'Sites that fight back meet adaptive selectors that re-learn layouts within policy, plus polite-crawl defaults baked in.',
    ],
    developer: 'Minion Systems',
    category: 'Agents & Automation',
    tags: ['scraping', 'automation', 'pipeline', 'no-code'],
    rating: 4.2,
    ratingCount: 2450,
    downloads: 79300,
    sizeMB: 26.8,
    version: '2.7.0',
    updatedDaysAgo: 12,
    colors: ['#f97316', '#facc15'],
    icon: 'Bug',
    features: ['Click-to-extract visual builder', 'Adaptive selector healing', 'Polite crawl defaults'],
    permissions: ["Outbound fetches you configure","Local pipeline storage"],
    changelog: [{ v: '2.7.0', notes: ['Pagination loop DSL'] }],
  },
  {
    id: 'meeting-minion',
    name: 'MeetingMinion',
    tagline: 'Notes, decisions and nudges from meetings',
    description: [
      'MeetingMinion joins calls, produces minutes with speaker-attributed decisions and open questions, then chases the follow-ups it created until they\u2019re done or renegotiated.',
      'Privacy mode keeps transcripts on-device; summaries sync as plain markdown your tools already understand.',
    ],
    developer: 'Cozy Compute',
    category: 'Agents & Automation',
    tags: ['meetings', 'notes', 'agent', 'follow-up'],
    rating: 4.4,
    ratingCount: 3960,
    downloads: 127600,
    sizeMB: 20.3,
    version: '2.1.0',
    updatedDaysAgo: 8,
    colors: ['#a855f7', '#6366f1'],
    icon: 'Presentation',
    features: ['Decision + open-question extraction', 'Autonomous follow-up nudges', 'On-device transcript privacy mode'],
    permissions: ["Microphone during meetings (opt-in)","On-device transcript storage"],
    changelog: [{ v: '2.1.0', notes: ['Renegotiation detection'] }],
  },
  {
    id: 'cronwright',
    name: 'Cronwright',
    tagline: 'Natural-language cron with guardrails',
    description: [
      'Describe a schedule in plain words \u2014 "weekdays at 9, skip holidays, never during backups" \u2014 and Cronwright compiles it to verifiable cron syntax with a calendar preview of the next hundred runs.',
      'Guardrails catch the classics: DST jumps, month-length traps and overlapping long-running jobs.',
    ],
    developer: 'Token Forge Studio',
    category: 'Agents & Automation',
    tags: ['cron', 'scheduling', 'cli', 'devops'],
    rating: 4.6,
    ratingCount: 1810,
    downloads: 45700,
    sizeMB: 3.2,
    version: '1.3.1',
    updatedDaysAgo: 21,
    colors: ['#10b981', '#3b82f6'],
    icon: 'CalendarClock',
    features: ['Plain-language to cron compiler', 'Next-100-runs calendar preview', 'Overlap and DST guardrails'],
    changelog: [{ v: '1.3.1', notes: ['Holiday calendar packs'] }],
  },
]

export const COLLECTIONS = [
  {
    title: 'Weekend MVP Kit',
    blurb: 'Four pieces between idea and launch',
    ids: ['formflow-studio', 'pulse-analytics', 'onboardly', 'market-mosaic'],
  },
  {
    title: 'Terminal Power Hour',
    blurb: 'Live entirely inside a rectangle',
    ids: ['warpfile', 'gitsage', 'syspulse-tui', 'notesmith'],
  },
  {
    title: 'Eval Before You Ship',
    blurb: 'Quality gates for generated software',
    ids: ['evaldeck', 'redteam-range', 'tracelens', 'benchlite'],
  },
  {
    title: 'Cozy Corner',
    blurb: 'Software that lowers your heart rate',
    ids: ['pixel-pet-hotel', 'habit-graph', 'wordforge-daily', 'carbon-lens'],
  },
]

export const DEVELOPER_AVATARS: Record<string, string> = {}

export function getApp(id: string): App | undefined {
  return APPS.find((a) => a.id === id)
}

export function similarApps(app: App, limit = 6): App[] {
  return APPS.filter((a) => a.id !== app.id)
    .map((a) => {
      let score = 0
      if (a.category === app.category) score += 3
      score += a.tags.filter((t) => app.tags.includes(t)).length
      score += a.developer === app.developer ? 1 : 0
      return { a, score }
    })
    .sort((x, y) => y.score - x.score || y.a.rating - x.a.rating)
    .slice(0, limit)
    .map((x) => x.a)
}

export function searchApps(query: string): App[] {
  const q = query.trim().toLowerCase()
  if (!q) return []
  const terms = q.split(/\s+/)
  return APPS.map((app) => {
    const haystack = [app.name, app.tagline, app.developer, app.category, ...app.tags].join(' ').toLowerCase()
    let score = 0
    for (const term of terms) {
      if (app.name.toLowerCase().includes(term)) score += 4
      else if (haystack.includes(term)) score += 1
    }
    return { app, score }
  })
    .filter((x) => x.score > 0)
    .sort((a, b) => b.score - a.score || b.app.downloads - a.app.downloads)
    .map((x) => x.app)
}
