import { mkdirSync, writeFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { catalogStats, stamp, isoWeek } from './lib/catalog.mjs'

const root = join(dirname(fileURLToPath(import.meta.url)), '..', '..')
const outDir = join(root, 'content', 'reports')
mkdirSync(outDir, { recursive: true })

const stats = catalogStats()
const { year, week } = isoWeek()

const body = [
  `# Weekly report — ${year} W${String(week).padStart(2, '0')} (${stamp()})`,
  ``,
  `## Catalog health (measured)`,
  ``,
  `- Listings: ${stats.listings}`,
  `- Runnable demos: ${stats.runnableDemos}/${stats.listings} (${stats.demoCoverage}% — beta-exit gate ≥60%)`,
  `- Collections: ${stats.collections}`,
  `- Average rating: ${stats.avgRating}`,
  `- Editors' picks: ${stats.editorsPicks}`,
  ``,
  `Per-category: ${Object.entries(stats.perCategory).map(([k, v]) => `${k} ${v}`).join(' · ')}`,
  ``,
  `## Funnel KPIs (targets from MARKETING_PLAN §6)`,
  ``,
  `| Metric | This week | Beta exit target | Status |`,
  `|---|---|---|---|`,
  `| WAU | UNMEASURED | 2.5k | instrumentation pending |`,
  `| Demo→install conversion | UNMEASURED | baseline | instrumentation pending |`,
  `| D30 retention | UNMEASURED | baseline | instrumentation pending |`,
  `| Organic share of signups | UNMEASURED | ≥50% | instrumentation pending |`,
  `| Listings with runnable demo | ${stats.demoCoverage}% | ≥60% | ${stats.demoCoverage >= 60 ? 'ON TRACK' : 'BELOW'} |`,
  `| Paying Studio teams | 0 (no payments rail) | 3 | pre-revenue by design |`,
  ``,
  `## Weakest stage & this week's experiment`,
  ``,
  `Funnel telemetry is not wired yet, so the honest weakest stage is **measurement itself**.`,
  `Experiment for this week: ship opt-in, privacy-preserving demo-play and install events`,
  `(localStorage queue + batched beacon) so next Monday's report can name a real funnel stage.`,
  ``,
  `_Generated by scripts/agents/analyst.mjs. UNMEASURED rows are deliberate — no vanity numbers._`,
]

const target = join(outDir, `weekly-${year}-W${String(week).padStart(2, '0')}.md`)
writeFileSync(target, body.join('\n'))
console.log(`wrote ${target}`)
