import { mkdirSync, writeFileSync, existsSync, readFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { editorsPicks, topDownloads, stamp } from './lib/catalog.mjs'

const root = join(dirname(fileURLToPath(import.meta.url)), '..', '..')
const outDir = join(root, 'content', 'queue')
mkdirSync(outDir, { recursive: true })

const url = (path = '') => `${process.env.SITE_URL ?? 'https://forge.example'}${path}`

function post(app) {
  const demo = app.demoId ? `Try it running in the listing: ${url(`/app/${app.id}`)}` : `Listing: ${url(`/app/${app.id}`)}`
  return [
    `### ${app.name} — ${app.tagline}`,
    ``,
    `${app.description[0].split('. ')[0]}.`,
    ``,
    `- Category: ${app.category} · by ${app.developer} · v${app.version}`,
    `- Rating ${app.rating.toFixed(1)} ★ (${Intl.NumberFormat('en', { notation: 'compact' }).format(app.ratingCount)} ratings)`,
    `- ${demo}`,
    ``,
    `> Every listing on Forge runs live before you install — sandboxed in your browser, verified against a signed build.`,
  ]
}

const featured = [...editorsPicks(), ...topDownloads(6).filter((a) => !a.editorsChoice)].slice(0, 4)

const body = [
  `# Social drafts — ${stamp()}`,
  ``,
  `Generated by scripts/agents/social.mjs from catalog data. Deterministic template mode`,
  `(no model key configured). Edit freely before posting; ledger-safe claims only.`,
  ``,
  ...featured.flatMap((app) => [...post(app), ``, `---`, ``]),
  `## Evergreen reply snippets`,
  ``,
  `- "How do demos stay safe?" → Opaque-origin sandboxed iframes, zero network egress, ed25519-signed artifacts. Verify yourself: \`npm run verify\`.`,
  `- "Where do files go when I sync?" → Your folders, or your own GitHub repo. Forge stores only SHA-256 manifests.`,
  `- "What does it cost?" → Listings are free; developers keep 85% on paid apps.`,
]

const target = join(outDir, `${stamp()}-social.md`)
if (existsSync(target) && readFileSync(target, 'utf8').includes('APPROVED-READY')) {
  console.log(`skipped ${target} — approved draft is immutable to agents`)
  process.exit(0)
}
writeFileSync(target, body.join('\n'))
console.log(`wrote ${target} (${featured.length} posts)`)
